name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: git config --global user.name "officialputuid" && git config --global user.email officialputuid@hack.id

      - name: Setup Android Build Environment
        run: |
          git clone https://github.com/akhilnarang/scripts
          cd scripts/setup
          bash android_build_env.sh

      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@maste
